// MÓDULO 6: NATUREZA/ROUPAS - 37 SINAIS
const modulo6_signals = [
    { id: 1, title: "TEMPO/CLIMA", video: "NATUREZA_ROUPAS/1_TEMPO_CLIMA.mp4", alt: "Avatar fazendo o sinal de Tempo/Clima", context: "Usado para se referir ao tempo ou clima" },
    { id: 2, title: "CALOR", video: "NATUREZA_ROUPAS/2_CALOR.mp4", alt: "Avatar fazendo o sinal de Calor", context: "Usado para indicar calor" },
    { id: 3, title: "FRIO", video: "NATUREZA_ROUPAS/3_FRIO.mp4", alt: "Avatar fazendo o sinal de Frio", context: "Usado para indicar frio" },
    { id: 4, title: "CHUVA", video: "NATUREZA_ROUPAS/4_CHUVA.mp4", alt: "Avatar fazendo o sinal de Chuva", context: "Usado para indicar chuva" },
    { id: 5, title: "VENTO", video: "NATUREZA_ROUPAS/5_VENTO.mp4", alt: "Avatar fazendo o sinal de Vento", context: "Usado para indicar vento" },
    { id: 6, title: "FLOR", video: "NATUREZA_ROUPAS/6_FLOR.mp4", alt: "Avatar fazendo o sinal de Flor", context: "Usado para se referir à flor" },
    { id: 7, title: "ÁRVORE", video: "NATUREZA_ROUPAS/7_ÁRVORE.mp4", alt: "Avatar fazendo o sinal de Árvore", context: "Usado para se referir à árvore" },
    { id: 8, title: "TERRA", video: "NATUREZA_ROUPAS/8_TERRA.mp4", alt: "Avatar fazendo o sinal de Terra", context: "Usado para se referir à terra" },
    { id: 9, title: "SOL", video: "NATUREZA_ROUPAS/9_SOL.mp4", alt: "Avatar fazendo o sinal de Sol", context: "Usado para se referir ao sol" },
    { id: 10, title: "ÁGUA", video: "NATUREZA_ROUPAS/10_ÁGUA.mp4", alt: "Avatar fazendo o sinal de Água", context: "Usado para se referir à água" },
    { id: 11, title: "RIO", video: "NATUREZA_ROUPAS/11_RIO.mp4", alt: "Avatar fazendo o sinal de Rio", context: "Usado para se referir ao rio" },
    { id: 12, title: "MAR", video: "NATUREZA_ROUPAS/12_MAR.mp4", alt: "Avatar fazendo o sinal de Mar", context: "Usado para se referir ao mar" },
    { id: 13, title: "LUA", video: "NATUREZA_ROUPAS/13_LUA.mp4", alt: "Avatar fazendo o sinal de Lua", context: "Usado para se referir à lua" },
    { id: 14, title: "ESTRELA", video: "NATUREZA_ROUPAS/14_ESTRELA.mp4", alt: "Avatar fazendo o sinal de Estrela", context: "Usado para se referir à estrela" },
    { id: 15, title: "GRAMA", video: "NATUREZA_ROUPAS/15_GRAMA.mp4", alt: "Avatar fazendo o sinal de Grama", context: "Usado para se referir à grama" },
    { id: 16, title: "VIAGEM/VIAJAR", video: "NATUREZA_ROUPAS/16_VIAGEM_VIAJAR.mp4", alt: "Avatar fazendo o sinal de Viagem/Viajar", context: "Usado para indicar viagem" },
    { id: 17, title: "ROUPAS", video: "NATUREZA_ROUPAS/17_ROUPAS.mp4", alt: "Avatar fazendo o sinal de Roupas", context: "Usado para se referir a roupas" },
    { id: 18, title: "CAMISETA", video: "NATUREZA_ROUPAS/18_CAMISETA.mp4", alt: "Avatar fazendo o sinal de Camiseta", context: "Usado para se referir à camiseta" },
    { id: 19, title: "SAIA", video: "NATUREZA_ROUPAS/19_SAIA.mp4", alt: "Avatar fazendo o sinal de Saia", context: "Usado para se referir à saia" },
    { id: 20, title: "VESTIDO", video: "NATUREZA_ROUPAS/20_VESTIDO.mp4", alt: "Avatar fazendo o sinal de Vestido", context: "Usado para se referir ao vestido" },
    { id: 21, title: "SAPATO", video: "NATUREZA_ROUPAS/21_SAPATO.mp4", alt: "Avatar fazendo o sinal de Sapato", context: "Usado para se referir ao sapato" },
    { id: 22, title: "CALÇA", video: "NATUREZA_ROUPAS/22_CALÇA.mp4", alt: "Avatar fazendo o sinal de Calça", context: "Usado para se referir à calça" },
    { id: 23, title: "BERMUDA", video: "NATUREZA_ROUPAS/23_BERMUDA.mp4", alt: "Avatar fazendo o sinal de Bermuda", context: "Usado para se referir à bermuda" },
    { id: 24, title: "DÚVIDA", video: "NATUREZA_ROUPAS/24_DÚVIDA.mp4", alt: "Avatar fazendo o sinal de Dúvida", context: "Usado para indicar dúvida" },
    { id: 25, title: "PACIÊNCIA", video: "NATUREZA_ROUPAS/25_PACIÊNCIA.mp4", alt: "Avatar fazendo o sinal de Paciência", context: "Usado para indicar paciência" },
    { id: 26, title: "VERDADE", video: "NATUREZA_ROUPAS/26_VERDADE.mp4", alt: "Avatar fazendo o sinal de Verdade", context: "Usado para indicar verdade" },
    { id: 27, title: "MENTIRA", video: "NATUREZA_ROUPAS/27_MENTIRA.mp4", alt: "Avatar fazendo o sinal de Mentira", context: "Usado para indicar mentira" },
    { id: 28, title: "CALMA", video: "NATUREZA_ROUPAS/28_CALMA.mp4", alt: "Avatar fazendo o sinal de Calma", context: "Usado para indicar calma" },
    { id: 29, title: "NERVOSO", video: "NATUREZA_ROUPAS/29_NERVOSO.mp4", alt: "Avatar fazendo o sinal de Nervoso", context: "Usado para indicar nervosismo" },
    { id: 30, title: "PREOCUPAR", video: "NATUREZA_ROUPAS/30_PREOCUPAR.mp4", alt: "Avatar fazendo o sinal de Preocupar", context: "Usado para indicar preocupação" },
    { id: 31, title: "LEVAR", video: "NATUREZA_ROUPAS/31_LEVAR.mp4", alt: "Avatar fazendo o sinal de Levar", context: "Usado para indicar ação de levar" },
    { id: 32, title: "SAIR/IR", video: "NATUREZA_ROUPAS/32_SAIR_IR.mp4", alt: "Avatar fazendo o sinal de Sair/Ir", context: "Usado para indicar ação de sair ou ir" },
    { id: 33, title: "CHEGAR", video: "NATUREZA_ROUPAS/33_CHEGAR.mp4", alt: "Avatar fazendo o sinal de Chegar", context: "Usado para indicar chegada" },
    { id: 34, title: "SUMIR", video: "NATUREZA_ROUPAS/34_SUMIR.mp4", alt: "Avatar fazendo o sinal de Sumir", context: "Usado para indicar desaparecimento" },
    { id: 35, title: "COMEÇAR", video: "NATUREZA_ROUPAS/35_COMEÇAR.mp4", alt: "Avatar fazendo o sinal de Começar", context: "Usado para indicar início" },
    { id: 36, title: "TERMINAR", video: "NATUREZA_ROUPAS/36_TERMINAR.mp4", alt: "Avatar fazendo o sinal de Terminar", context: "Usado para indicar término" },
    { id: 37, title: "ESCOLHER", video: "NATUREZA_ROUPAS/37_ESCOLHER.mp4", alt: "Avatar fazendo o sinal de Escolher", context: "Usado para indicar escolha" },
    { id: 38, title: "ESPERAR", video: "NATUREZA_ROUPAS/38_ESPERAR.mp4", alt: "Avatar fazendo o sinal de Esperar", context: "Usado para indicar espera" }
];
